export interface SymbolItem {
  char: string;
  name: string;
  code?: string;
}

export const ARROWS_SYMBOLS: SymbolItem[] = [
  { char: '←', name: 'Leftwards Arrow', code: 'U+2190' },
  { char: '↑', name: 'Upwards Arrow', code: 'U+2191' },
  { char: '→', name: 'Rightwards Arrow', code: 'U+2192' },
  { char: '↓', name: 'Downwards Arrow', code: 'U+2193' },
  { char: '↔', name: 'Left Right Arrow', code: 'U+2194' },
  { char: '↕', name: 'Up Down Arrow', code: 'U+2195' },
  { char: '↖', name: 'North West Arrow', code: 'U+2196' },
  { char: '↗', name: 'North East Arrow', code: 'U+2197' },
  { char: '↘', name: 'South East Arrow', code: 'U+2198' },
  { char: '↙', name: 'South West Arrow', code: 'U+2199' },
  { char: '⇐', name: 'Leftwards Double Arrow', code: 'U+21D0' },
  { char: '⇑', name: 'Upwards Double Arrow', code: 'U+21D1' },
  { char: '⇒', name: 'Rightwards Double Arrow', code: 'U+21D2' },
  { char: '⇓', name: 'Downwards Double Arrow', code: 'U+21D3' },
  { char: '⇔', name: 'Left Right Double Arrow', code: 'U+21D4' },
  { char: '⇕', name: 'Up Down Double Arrow', code: 'U+21D5' },
  { char: '➔', name: 'Heavy Rightwards Arrow', code: 'U+2794' },
  { char: '➜', name: 'Heavy Round-Tipped Right Arrow', code: 'U+279C' },
  { char: '➤', name: 'Black Rightwards Arrowhead', code: 'U+27A4' },
  { char: '➥', name: 'Heavy Lower Right-弯 Arrow', code: 'U+27A5' },
  { char: '➦', name: 'Heavy Upper Right-弯 Arrow', code: 'U+27A6' },
  { char: '⤴', name: 'Arrow Pointing Rightwards Then Curving Up', code: 'U+2934' },
  { char: '⤵', name: 'Arrow Pointing Rightwards Then Curving Down', code: 'U+2935' },
  { char: '⇄', name: 'Rightwards Arrow Over Leftwards Arrow', code: 'U+21C4' },
  { char: '⇅', name: 'Upwards Arrow Left of Downwards Arrow', code: 'U+21C5' },
  { char: '⇆', name: 'Leftwards Arrow Over Rightwards Arrow', code: 'U+21C6' },
  { char: '⇇', name: 'Leftwards Paired Arrows', code: 'U+21C7' },
  { char: '⇉', name: 'Rightwards Paired Arrows', code: 'U+21C9' },
  { char: '↩', name: 'Leftwards Arrow with Hook (Return)', code: 'U+21A9' },
  { char: '↪', name: 'Rightwards Arrow with Hook', code: 'U+21AA' },
];

export const MATH_SYMBOLS: SymbolItem[] = [
  { char: '±', name: 'Plus-Minus Sign', code: 'U+00B1' },
  { char: '×', name: 'Multiplication Sign', code: 'U+00D7' },
  { char: '÷', name: 'Division Sign', code: 'U+00F7' },
  { char: '≠', name: 'Not Equal To', code: 'U+2260' },
  { char: '≈', name: 'Almost Equal To', code: 'U+2248' },
  { char: '≤', name: 'Less-Than or Equal To', code: 'U+2264' },
  { char: '≥', name: 'Greater-Than or Equal To', code: 'U+2265' },
  { char: '∞', name: 'Infinity', code: 'U+221E' },
  { char: '∑', name: 'N-Ary Summation', code: 'U+2211' },
  { char: '∏', name: 'N-Ary Product', code: 'U+220F' },
  { char: '√', name: 'Square Root', code: 'U+221A' },
  { char: '∫', name: 'Integral', code: 'U+222B' },
  { char: '∂', name: 'Partial Differential', code: 'U+2202' },
  { char: 'Δ', name: 'Greek Capital Letter Delta / Increment', code: 'U+0394' },
  { char: '∇', name: 'Nabla / Del Operator', code: 'U+2207' },
  { char: '∈', name: 'Element Of', code: 'U+2208' },
  { char: '∉', name: 'Not An Element Of', code: 'U+2209' },
  { char: '⊂', name: 'Subset Of', code: 'U+2282' },
  { char: '⊃', name: 'Superset Of', code: 'U+2283' },
  { char: '∪', name: 'Union', code: 'U+222A' },
  { char: '∩', name: 'Intersection', code: 'U+2229' },
  { char: '∅', name: 'Empty Set', code: 'U+2205' },
  { char: '‰', name: 'Per Mille Sign', code: 'U+2030' },
  { char: '‱', name: 'Per Ten Thousand Sign (Basis Point)', code: 'U+2031' },
  { char: '∝', name: 'Proportional To', code: 'U+221D' },
  { char: '∠', name: 'Angle', code: 'U+2220' },
  { char: '∟', name: 'Right Angle', code: 'U+221F' },
  { char: '∧', name: 'Logical And', code: 'U+2227' },
  { char: '∨', name: 'Logical Or', code: 'U+2228' },
  { char: '¬', name: 'Not Sign', code: 'U+00AC' },
  { char: '⊕', name: 'Circled Plus / XOR', code: 'U+2295' },
  { char: '⊗', name: 'Circled Times / Tensor', code: 'U+2297' },
  { char: '⊥', name: 'Up Tack / Perpendicular', code: 'U+22A5' },
  { char: '∴', name: 'Therefore', code: 'U+2234' },
  { char: '∵', name: 'Because', code: 'U+2235' },
  { char: '≡', name: 'Identical To / Equivalent', code: 'U+2261' },
  { char: '≢', name: 'Not Identical To', code: 'U+2262' },
  { char: '∼', name: 'Tilde Operator / Similar', code: 'U+223C' },
  { char: '≅', name: 'Approximately Equal / Congruent', code: 'U+2245' },
  { char: '∀', name: 'For All', code: 'U+2200' },
];

export const CURRENCY_SYMBOLS: SymbolItem[] = [
  { char: '$', name: 'Dollar Sign', code: 'U+0024' },
  { char: '€', name: 'Euro Sign', code: 'U+20AC' },
  { char: '£', name: 'Pound Sign', code: 'U+00A3' },
  { char: '¥', name: 'Yen / Yuan Sign', code: 'U+00A5' },
  { char: '₹', name: 'Indian Rupee Sign', code: 'U+20B9' },
  { char: '₽', name: 'Russian Ruble Sign', code: 'U+20BD' },
  { char: '₩', name: 'Won Sign', code: 'U+20A9' },
  { char: '₺', name: 'Turkish Lira Sign', code: 'U+20BA' },
  { char: '₴', name: 'Hryvnia Sign (Ukraine)', code: 'U+20B4' },
  { char: '₫', name: 'Dong Sign (Vietnam)', code: 'U+20AB' },
  { char: '฿', name: 'Thai Baht Sign', code: 'U+0E3F' },
  { char: '₡', name: 'Colon Sign (Costa Rica)', code: 'U+20A1' },
  { char: '₲', name: 'Guarani Sign (Paraguay)', code: 'U+20B2' },
  { char: '₵', name: 'Cedi Sign (Ghana)', code: 'U+20B5' },
  { char: '₦', name: 'Naira Sign (Nigeria)', code: 'U+20A6' },
  { char: '₪', name: 'New Israeli Sheqel', code: 'U+20AA' },
  { char: '₸', name: 'Tenge Sign (Kazakhstan)', code: 'U+20B8' },
  { char: '₼', name: 'Manat Sign (Azerbaijan)', code: 'U+20BC' },
  { char: '₿', name: 'Bitcoin Sign', code: 'U+20BF' },
  { char: 'Ξ', name: 'Ethereum Symbol (Xi)', code: 'U+039E' },
  { char: '¢', name: 'Cent Sign', code: 'U+00A2' },
  { char: '¤', name: 'Currency Sign (Generic)', code: 'U+00A4' },
  { char: '元', name: 'Chinese Yuan Hanzi', code: 'U+5143' },
  { char: '円', name: 'Japanese Yen Kanji', code: 'U+5186' },
];

export const LEGAL_SYMBOLS: SymbolItem[] = [
  { char: '©', name: 'Copyright Sign', code: 'U+00A9' },
  { char: '®', name: 'Registered Sign', code: 'U+00AE' },
  { char: '™', name: 'Trade Mark Sign', code: 'U+2122' },
  { char: '§', name: 'Section Sign', code: 'U+00A7' },
  { char: '¶', name: 'Pilcrow / Paragraph Sign', code: 'U+00B6' },
  { char: '†', name: 'Dagger', code: 'U+2020' },
  { char: '‡', name: 'Double Dagger', code: 'U+2021' },
  { char: '℠', name: 'Service Mark', code: 'U+2120' },
  { char: '№', name: 'Numero Sign', code: 'U+2116' },
  { char: '℗', name: 'Sound Recording Copyright', code: 'U+2117' },
  { char: '℅', name: 'Care Of', code: 'U+2105' },
  { char: '‰', name: 'Per Mille Sign', code: 'U+2030' },
  { char: 'ℓ', name: 'Script Small L (Litre)', code: 'U+2113' },
  { char: '℀', name: 'Account Of', code: 'U+2100' },
  { char: '℁', name: 'Addressed To The Subject', code: 'U+2101' },
  { char: '℃', name: 'Degree Celsius', code: 'U+2103' },
  { char: '℉', name: 'Degree Fahrenheit', code: 'U+2109' },
  { char: '°', name: 'Degree Sign', code: 'U+00B0' },
  { char: 'µ', name: 'Micro Sign', code: 'U+00B5' },
  { char: '·', name: 'Middle Dot', code: 'U+00B7' },
  { char: '•', name: 'Bullet Point', code: 'U+2022' },
  { char: '…', name: 'Horizontal Ellipsis', code: 'U+2026' },
  { char: '–', name: 'En Dash', code: 'U+2013' },
  { char: '—', name: 'Em Dash', code: 'U+2014' },
  { char: '«', name: 'Left-Pointing Double Angle Quotation', code: 'U+00AB' },
  { char: '»', name: 'Right-Pointing Double Angle Quotation', code: 'U+00BB' },
  { char: '“', name: 'Left Double Quotation Mark', code: 'U+201C' },
  { char: '”', name: 'Right Double Quotation Mark', code: 'U+201D' },
  { char: '‘', name: 'Left Single Quotation Mark', code: 'U+2018' },
  { char: '’', name: 'Right Single Quotation Mark', code: 'U+2019' },
];

export const GREEK_SYMBOLS: SymbolItem[] = [
  { char: 'α', name: 'Greek Small Letter Alpha', code: 'U+03B1' },
  { char: 'β', name: 'Greek Small Letter Beta', code: 'U+03B2' },
  { char: 'γ', name: 'Greek Small Letter Gamma', code: 'U+03B3' },
  { char: 'δ', name: 'Greek Small Letter Delta', code: 'U+03B4' },
  { char: 'ε', name: 'Greek Small Letter Epsilon', code: 'U+03B5' },
  { char: 'ζ', name: 'Greek Small Letter Zeta', code: 'U+03B6' },
  { char: 'η', name: 'Greek Small Letter Eta', code: 'U+03B7' },
  { char: 'θ', name: 'Greek Small Letter Theta', code: 'U+03B8' },
  { char: 'ι', name: 'Greek Small Letter Iota', code: 'U+03B9' },
  { char: 'κ', name: 'Greek Small Letter Kappa', code: 'U+03BA' },
  { char: 'λ', name: 'Greek Small Letter Lambda', code: 'U+03BB' },
  { char: 'μ', name: 'Greek Small Letter Mu', code: 'U+03BC' },
  { char: 'ν', name: 'Greek Small Letter Nu', code: 'U+03BD' },
  { char: 'ξ', name: 'Greek Small Letter Xi', code: 'U+03BE' },
  { char: 'ο', name: 'Greek Small Letter Omicron', code: 'U+03BF' },
  { char: 'π', name: 'Greek Small Letter Pi', code: 'U+03C0' },
  { char: 'ρ', name: 'Greek Small Letter Rho', code: 'U+03C1' },
  { char: 'σ', name: 'Greek Small Letter Sigma', code: 'U+03C3' },
  { char: 'τ', name: 'Greek Small Letter Tau', code: 'U+03C4' },
  { char: 'υ', name: 'Greek Small Letter Upsilon', code: 'U+03C5' },
  { char: 'φ', name: 'Greek Small Letter Phi', code: 'U+03C6' },
  { char: 'χ', name: 'Greek Small Letter Chi', code: 'U+03C7' },
  { char: 'ψ', name: 'Greek Small Letter Psi', code: 'U+03C8' },
  { char: 'ω', name: 'Greek Small Letter Omega', code: 'U+03C9' },
  { char: 'Α', name: 'Greek Capital Letter Alpha', code: 'U+0391' },
  { char: 'Β', name: 'Greek Capital Letter Beta', code: 'U+0392' },
  { char: 'Γ', name: 'Greek Capital Letter Gamma', code: 'U+0393' },
  { char: 'Δ', name: 'Greek Capital Letter Delta', code: 'U+0394' },
  { char: 'Ε', name: 'Greek Capital Letter Epsilon', code: 'U+0395' },
  { char: 'Ζ', name: 'Greek Capital Letter Zeta', code: 'U+0396' },
  { char: 'Η', name: 'Greek Capital Letter Eta', code: 'U+0397' },
  { char: 'Θ', name: 'Greek Capital Letter Theta', code: 'U+0398' },
  { char: 'Ι', name: 'Greek Capital Letter Iota', code: 'U+0399' },
  { char: 'Κ', name: 'Greek Capital Letter Kappa', code: 'U+039A' },
  { char: 'Λ', name: 'Greek Capital Letter Lambda', code: 'U+039B' },
  { char: 'Μ', name: 'Greek Capital Letter Mu', code: 'U+039C' },
  { char: 'Ν', name: 'Greek Capital Letter Nu', code: 'U+039D' },
  { char: 'Ξ', name: 'Greek Capital Letter Xi', code: 'U+039E' },
  { char: 'Ο', name: 'Greek Capital Letter Omicron', code: 'U+039F' },
  { char: 'Π', name: 'Greek Capital Letter Pi', code: 'U+03A0' },
  { char: 'Ρ', name: 'Greek Capital Letter Rho', code: 'U+03A1' },
  { char: 'Σ', name: 'Greek Capital Letter Sigma', code: 'U+03A3' },
  { char: 'Τ', name: 'Greek Capital Letter Tau', code: 'U+03A4' },
  { char: 'Υ', name: 'Greek Capital Letter Upsilon', code: 'U+03A5' },
  { char: 'Φ', name: 'Greek Capital Letter Phi', code: 'U+03A6' },
  { char: 'Χ', name: 'Greek Capital Letter Chi', code: 'U+03A7' },
  { char: 'Ψ', name: 'Greek Capital Letter Psi', code: 'U+03A8' },
  { char: 'Ω', name: 'Greek Capital Letter Omega', code: 'U+03A9' },
];

export const EMOJI_SYMBOLS: SymbolItem[] = [
  { char: '😀', name: 'Grinning Face' },
  { char: '😃', name: 'Smiling Face with Big Eyes' },
  { char: '😊', name: 'Smiling Face with Smiling Eyes' },
  { char: '👍', name: 'Thumbs Up' },
  { char: '👎', name: 'Thumbs Down' },
  { char: '❤️', name: 'Red Heart' },
  { char: '🔥', name: 'Fire / Trend' },
  { char: '⭐', name: 'Star' },
  { char: '🎉', name: 'Party Popper / Celebration' },
  { char: '💡', name: 'Light Bulb / Idea' },
  { char: '✅', name: 'Check Mark Button' },
  { char: '❌', name: 'Cross Mark' },
  { char: '⚠️', name: 'Warning' },
  { char: '🚀', name: 'Rocket / Launch' },
  { char: '📌', name: 'Pushpin' },
  { char: '✨', name: 'Sparkles' },
  { char: '💼', name: 'Briefcase / Business' },
  { char: '📝', name: 'Memo / Document' },
  { char: '📅', name: 'Calendar' },
  { char: '🎯', name: 'Direct Hit / Goal' },
  { char: '👏', name: 'Clapping Hands' },
  { char: '🤝', name: 'Handshake' },
  { char: '🏆', name: 'Trophy / Winner' },
  { char: '💯', name: 'Hundred Points' },
  { char: '⚡', name: 'High Voltage / Fast' },
  { char: '🔍', name: 'Magnifying Glass Tilt Left' },
  { char: '🔒', name: 'Locked' },
  { char: '🔔', name: 'Bell / Alert' },
  { char: '📈', name: 'Chart Increasing' },
  { char: '📉', name: 'Chart Decreasing' },
];
